---
title: Assignment 2 Energy Project Economics
format: 
  html: 
    theme: cosmo
    css: /styles.css
    toc: true
    link-external-icon: true
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
#draft: true
---

## 1. A Tale of Two Nuclear Plants

### Background  

Please read the stories about the [Shoreham Nuclear Power Plant](https://en.wikipedia.org/wiki/Shoreham_Nuclear_Power_Plant) and the [Diablo Canyon Power Plant](https://en.wikipedia.org/wiki/Diablo_Canyon_Power_Plant)--two nuclear projects with contrasting outcomes. Shoreham was decommisioned without even operating commercially, leaving Long Islandrate-payers to cover its costs, Diablo Canyon was offered to extend operation as part of California's clean energy transition.


### Questions

1. **Shoreham Nuclear Power Plant**:

LILCO (Long Island Lighting Company) attaches a **3%** surcharge to Long Island electric bills for 30 years to pay off the nuclear facility’s approximately **$6 billion** price tag in 1989. 

How long does it take for Long Island residents to pay off Shoreham's construction and decommissioning costs? (Bad energy investment decisions could have drastic financial consequences)  (**2pt**)

Using the following assumptions to calculate the duration of ratepayer charges: 

- Initial cost(1989): **$6 billion**   
- Residential rates (2025): **23 cents/kWh**^[You can find more information about the Long Island electric rates here: https://www.psegliny.com/aboutpseglongisland/ratesandtariffs/rateinformation]   
- Long Island total electricity consumption (2025): **20 TWh**   
- Surcharge rate: **3%** of total electricity bills  
- Discount rate: **4%**   
- Assuming the real value of total annual surcharge remains constant. You can use 2025 as the base year, convert the 1989 $6 billion price tag to 2025 value, then calculate the total surchage revenue in 2025 and estimate how long it will take to pay off the cost.  


2. **Diablo Canyon Power Plant**:

In 2021, Diablo Canyon Power Plant generated nearly 9% of Cailifornia's electricity and roughly 15% of the State's clean energy production. The plant has been granted a 5 year extention beyond its scheduled closure in 2025. 

What's the levelized cost of electricity (LCOE) of Diablo Canyon for its extended operation period (2026-2030)?  (**2pt**)
 
Use the following assumptions:

- Nameplate capacity: **2,256 MW**   
- Capacity factor: **80%**   
- Discount rate: **4%**   
- Capical investment cost for extensioon: **$1.4** billion (forgivable loans, considered the only investment, past investments are sunk costs and should not be considered in this calculation).  
- Assuming the annual O&M costs are 3% of the investment costs, average fuel costs is [\$5.37/MWh]^[https://www.nei.org/CorporateSite/media/filefolder/resources/reports-and-briefs/2023-Costs-in-Context_r1.pdf]. 



## 2. What if Americans turn to small cars and electric vehicles?

America has a big car problem. This assignment gives you the opportunity to practice with data and policy analysis. You will navigate through common energy and carbon data, make reasonable assumptions, and calculate policy-relevant metrics. 

First, let's make some assumptions on the market penetration of small cars and electric vehicles: 

Key assumptions (all based on 2022 data):

- Average annual miles per vehicle: 11,000 miles^[https://afdc.energy.gov/data/10309]\
- Averge fuel efficiency^[https://thundersaidenergy.com/downloads/us-vehicle-sales-by-fuel-economy-cars-trucks-and-suvs]: \
  - Subcompact/small cars: 33 mile per gallon (mpg)\
  - Big cars/pickup trucks: 20 mpg\
- Total registerd personal and commercial vehicles: 278,870,463^[https://www.forbes.com/advisor/car-insurance/car-ownership-statistics]\
- Big cars (large, crossover, SUVs) market share: 65%^[https://www.autoinsurance.com/research/car-ownership-statistics/]\

### Questions

1. **Oil savings with a switch to smaller cars**: If the U.S. replaces half of its big cars (large, crossover, SUVs) with small cars (subcompact, compact, and midsize cars) in 2022, how much gasoline can the US save in one year? Compare your result with U.S. daily oil imports. (1pt)

2. **EV transition by 2050**: Assume the U.S. replaces all vehicles with EVs by 2050. How much gasoline could be avoided annually in 2050, compared to 2022? Additionally, how much more electricity would be required to charge all vehicles in a year? Assumming the total number of vehicles remains the same and the average combined efficiency of 25 kWh/100 miles^[https://en.wikipedia.org/wiki/Electric_car_EPA_fuel_economy] for EVs. (2pts)
 

## Further readings

Get to understand what composites the 6 billion price tag, and what are the hidden costs? Check the political economy of the energy policy and investment decisions.

New York Times, June 19, 1983. [How Long Island Will Pay For Shoreham](https://www.nytimes.com/1983/06/19/nyregion/how-li-will-pay-for-shoreham.html)  

Timothy Bolger and Christopher Twarowski, June 11, 2009, [Nuclear Waste: 20 Years After Shoreham’s Closure](http://archive.longislandpress.com/2009/06/11/nuclear-waste-20-years-after-the-closure-of-the-shoreham-power-facility/)

Nathan Rott, September 1, 2022. [California lawmakers extend the life of the state's last nuclear power plant](https://www.npr.org/2022/09/01/1119778975/california-lawmakers-extend-the-life-of-the-states-last-nuclear-power-plant)  





