project:
  type: website
  output-dir: docs

# meta
meta-description: "Energy, Climate, and Society, an undergraduate level energy and climate topic open course developed by Dr. Gang He."
meta-author: "Gang He"


website:
  title: "Energy, Climate, and Society"
  description: "Energy, Climate, and Society, an undergraduate level energy and climate topic open course developed by Dr. Gang He."
  navbar:
    background: light
    left:
      - text: Syllabus
        href: syllabus.qmd
      - text: Schedule
        href: 2025/schedule.qmd
      - text: Lectures
        href: lectures.qmd
      - text: Guest Speakers
        href: http://drganghe.github.io/climate-guest-speakers
        target: _blank 
      - text: Guide
        menu:                   
        - text: Mock Climate Negotiation
          href: mock-climate-negotiation.qmd        
        - text: Tools of the Trade
          href: tools.qmd  
        - text: Policy Memo
          href: policymemo.qmd          
        - text: Resources
          href: resources.qmd
      - text: Archive
        menu:
          - text: Fall 2023
            href: 2023/schedule.qmd           
      - text: Dr. Gang He
        href: http://drganghe.github.io        
    right: 
      - icon: github
        href: https://github.com/drganghe/energy-climate-society
  page-navigation: true
  page-footer: 
    left: "[Gang He](http://drganghe.github.io) &copy; <script>document.write(new Date().getFullYear())</script>" 
    right: 
      - icon: github
        href: https://github.com/drganghe/energy-climate-society
      - text: "{{< fa brands bluesky >}}" 
        href: https://bsky.app/profile/hegang.bsky.social
        target: _blank
  search:
    location: navbar
    type: textbox
  reader-mode: true
  repo-url: https://github.com/drganghe/energy-climate-society
  repo-actions: [edit, issue, source]
  open-graph: true
  twitter-card: true
  #  creator: "@DrGangHe"
  #  image: "/files/images/hex-Energy-Climate-Society.png"
  site-url: "https://drganghe.github.io/energy-climate-society"
  google-analytics:
    tracking-id: "G-9ZBRZBEKDN"  # Please delete or replace with your own tracking ID
    anonymize-ip: true

bibliography: readings.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
    #link-external-filter: '^(?:http:|https:)\/\/drganghe\.github\.io\/custom'

execute:
  freeze: auto

comments:
  hypothesis: false
  

