---
title: Policy Memo
format: 
  html: 
    theme: cosmo
 #   css: styles.css
    toc: true
    link-external-icon: false
    link-external-newwindow: true
  pdf: 
    documentclass: article
    #classoption: [landscape]
    lof: false
    lot: false
    geometry:
      - top=1in
      - bottom=1in
      - left=1in
      - right=1in
      - heightrounded
    #fontfamily: xelatex
    colorlinks: true
---

## Introduction

Your final project is a demonstration of your mastery of the concepts and skills discussed in the class. You can choose an energy-related topic of your own interest. In each lecture, I listed sample analytic questions of the chapter and I hope that offers you some inspiration. I also list some sample topics below.

### Sample policy memo topics

- What would be an optimal congestion price in NYC?
- Policies to enhance supply chains of offshore wind in NYS?
- What NYSERDA should do to promote heat pump installations?
- How to help disadvantaged communities adapt to climate change?


## Proposal

Please submit a one-page proposal letting me know your topic, briefly explaining why you chose it, what data and analytic methods you plan to use, and any potential challenges and how you would address them.


## Presentation

Your presentation should be about 15–20 minutes long, summarizing your work. Please record your presentation with your video on or face visible. 

Your presentation will be graded by the following criteria:

1. Nice presence [4pt]
2. Clear presentation of project ideas and insights [4pt]
3. Mastery of the subject [4pt]
4. Presentation design and style [4pt]
5. Overall impression [4pt]


## Policy Memo

A typical policy memo includes an introduction (topic or problem), scope of problem, current approach, **proposed approach/policies and evidences**, and conclusion. Your policy memo should be double-spaced and 2–3 pages long, excluding appropriately cited references. 

Your policy will be graded by the following criteria:

1. Creativity in defining a topic/problem [5pt]
2. Rigorous analysis [5pt]
3. Clear writing, presentation, visualization [5pt]
4. Overall impression [5pt]


## Student Projects

- [Spring 2025](/2025/students.qmd)
- [Fall 2023](/2023/students.qmd)


## References

[Policy Memo Resources](https://policymemos.hks.harvard.edu/home)

<!--Include social share buttons-->

{{< include /files/includes/_socialshare.qmd >}}
