---
title: Course Schedule
repo-actions: false
---


| Week | Tuesday  | Thursday  | Assignment     |
|-----------------|-----------------|---------------------|-----------------|
| 1    | 8/29, [Introduction](lectures/lecture1.qmd) |8/31, [Make sense of numbers](lectures/lecture2.qmd) | [HW1](assignments/hw1.qmd) assigned |
| 2    | 9/5, [Climate foudamentals](lectures/lecture3.qmd) | 9/7, [Climate impacts](lectures/lecture4.qmd)| |
| 3    | 9/12, [Tool: Social cost of carbon](tools/1scc.qmd) | 9/14, [Climate mitigation](lectures/lecture5.qmd)| |
| 4    | 9/19, [Climate adaptation](lectures/lecture6.qmd) | 9/21, [Energy systems](lectures/lecture7.qmd)| |
| 5    | 9/26, [Energy project economics](lectures/lecture8.qmd) | 9/28, [Fossil technologies](lectures/lecture9.qmd) | [HW2](assignments/hw2.qmd) assigned |
| 6    | 10/3, [Solar technologies](lectures/lecture10.qmd) | 10/5, [Wind technologies](lectures/lecture11.qmd) |  |
| 7    | 10/10, Monday schedule - No session | 10/12, [Tool: Solar wind assessment](tools/2sam.qmd)| |
| 8    | 10/17, [Nuclear, hydro, and other](lectures/lecture12.qmd) | 10/19, [Energy demand](lectures/lecture13.qmd) |[HW3](assignments/hw3.qmd) assigned |
| 9    | 10/24, [Energy efficiency](lectures/lecture14.qmd) | 10/26, [Energy access](lectures/lecture15.qmd) |  |
| 10    | 10/31, [Energy, environment, health](lectures/lecture16.qmd) | 11/2, [Energy transition](lectures/lecture17.qmd) |  |
| 11    | 11/7, [Tool: Pathways to net-zero](tools/3pathway.qmd) | 11/9, [Power systems](lectures/lecture18.qmd) | [HW4](assignments/hw4.qmd) assigned |
| 12    | 11/14, [Big data and AI](lectures/lecture19.qmd) | 11/16, [Life cycle analysis](lectures/lecture20.qmd) |  |
| 13    | 11/21, [Tool: Life cycle analysis](tools/4lca.qmd) | Thanksgiving - No session |  |
| 14    | 11/28, [Uncertainties and limitations](lectures/lecture21.qmd) | 11/30, [Review and summary](lectures/lecture22.qmd) |  |
| 15    | 12/5, Presentation | 12/7, Presentation | End of class |